CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Cargos" (
        id_cargo integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Cargos" PRIMARY KEY (id_cargo)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Libros" (
        id_libro integer GENERATED BY DEFAULT AS IDENTITY,
        nombre_libro character varying(255) NOT NULL,
        autor character varying(150) NOT NULL,
        isbn character varying(50) NOT NULL,
        genero character varying(100) NOT NULL,
        editorial character varying(100) NOT NULL,
        estado character varying(50) NOT NULL,
        CONSTRAINT "PK_Libros" PRIMARY KEY (id_libro)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Permisos" (
        id_permiso integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        codigo character varying(100) NOT NULL,
        CONSTRAINT "PK_Permisos" PRIMARY KEY (id_permiso)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Roles" (
        id_rol integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        descripcion character varying(500) NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY (id_rol)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Usuarios" (
        id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        apellido character varying(100) NOT NULL,
        cedula character varying(20) NOT NULL,
        numero_telefono character varying(20) NOT NULL,
        email character varying(100) NOT NULL,
        contrasena_hash character varying(255) NOT NULL,
        tipo_usuario character varying(50) NOT NULL,
        estado character varying(20) NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY (id_usuario)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Ejemplares" (
        id_ejemplar integer GENERATED BY DEFAULT AS IDENTITY,
        id_libro integer NOT NULL,
        codigo character varying(80) NOT NULL,
        estado character varying(30) NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Ejemplares" PRIMARY KEY (id_ejemplar),
        CONSTRAINT "FK_Ejemplares_Libros_id_libro" FOREIGN KEY (id_libro) REFERENCES "Libros" (id_libro) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Inventario" (
        id_inventario integer GENERATED BY DEFAULT AS IDENTITY,
        id_libro integer NOT NULL,
        cantidad_total integer NOT NULL,
        cantidad_disponible integer NOT NULL,
        cantidad_prestada integer NOT NULL,
        CONSTRAINT "PK_Inventario" PRIMARY KEY (id_inventario),
        CONSTRAINT "FK_Inventario_Libros_id_libro" FOREIGN KEY (id_libro) REFERENCES "Libros" (id_libro) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "RolPermiso" (
        id_rol integer NOT NULL,
        id_permiso integer NOT NULL,
        CONSTRAINT "PK_RolPermiso" PRIMARY KEY (id_rol, id_permiso),
        CONSTRAINT "FK_RolPermiso_Permisos_id_permiso" FOREIGN KEY (id_permiso) REFERENCES "Permisos" (id_permiso) ON DELETE RESTRICT,
        CONSTRAINT "FK_RolPermiso_Roles_id_rol" FOREIGN KEY (id_rol) REFERENCES "Roles" (id_rol) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Administradores" (
        id_administrador integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        id_cargo integer NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Administradores" PRIMARY KEY (id_administrador),
        CONSTRAINT "FK_Administradores_Cargos_id_cargo" FOREIGN KEY (id_cargo) REFERENCES "Cargos" (id_cargo) ON DELETE RESTRICT,
        CONSTRAINT "FK_Administradores_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Auditoria" (
        id_auditoria integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        modulo character varying(100) NOT NULL,
        accion character varying(100) NOT NULL,
        descripcion character varying(500) NOT NULL,
        resultado character varying(50) NOT NULL,
        fecha timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Auditoria" PRIMARY KEY (id_auditoria),
        CONSTRAINT "FK_Auditoria_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Empleados" (
        id_empleado integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        id_cargo integer NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Empleados" PRIMARY KEY (id_empleado),
        CONSTRAINT "FK_Empleados_Cargos_id_cargo" FOREIGN KEY (id_cargo) REFERENCES "Cargos" (id_cargo) ON DELETE RESTRICT,
        CONSTRAINT "FK_Empleados_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Notificaciones" (
        id_notificacion integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        mensaje character varying(500) NOT NULL,
        fecha_envio timestamp with time zone NOT NULL,
        leida boolean NOT NULL,
        tipo_evento character varying(100) NOT NULL,
        CONSTRAINT "PK_Notificaciones" PRIMARY KEY (id_notificacion),
        CONSTRAINT "FK_Notificaciones_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "SolicitudPrestamo" (
        id_solicitud integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        id_libro integer NOT NULL,
        fecha_solicitud timestamp with time zone NOT NULL,
        estado character varying(50) NOT NULL,
        motivo_rechazo character varying(255),
        CONSTRAINT "PK_SolicitudPrestamo" PRIMARY KEY (id_solicitud),
        CONSTRAINT "FK_SolicitudPrestamo_Libros_id_libro" FOREIGN KEY (id_libro) REFERENCES "Libros" (id_libro) ON DELETE RESTRICT,
        CONSTRAINT "FK_SolicitudPrestamo_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "UsuarioRol" (
        id_usuario integer NOT NULL,
        id_rol integer NOT NULL,
        CONSTRAINT "PK_UsuarioRol" PRIMARY KEY (id_usuario, id_rol),
        CONSTRAINT "FK_UsuarioRol_Roles_id_rol" FOREIGN KEY (id_rol) REFERENCES "Roles" (id_rol) ON DELETE RESTRICT,
        CONSTRAINT "FK_UsuarioRol_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Prestamos" (
        id_prestamo integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        id_libro integer NOT NULL,
        id_ejemplar integer NOT NULL,
        id_solicitud integer NOT NULL,
        id_empleado_prestamo integer NOT NULL,
        id_empleado_devolucion integer,
        fecha_prestamo timestamp with time zone NOT NULL,
        fecha_devolucion_esperada timestamp with time zone NOT NULL,
        fecha_devolucion timestamp with time zone,
        estado character varying(50) NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Prestamos" PRIMARY KEY (id_prestamo),
        CONSTRAINT "FK_Prestamos_Ejemplares_id_ejemplar" FOREIGN KEY (id_ejemplar) REFERENCES "Ejemplares" (id_ejemplar) ON DELETE RESTRICT,
        CONSTRAINT "FK_Prestamos_Empleados_id_empleado_devolucion" FOREIGN KEY (id_empleado_devolucion) REFERENCES "Empleados" (id_empleado) ON DELETE RESTRICT,
        CONSTRAINT "FK_Prestamos_Empleados_id_empleado_prestamo" FOREIGN KEY (id_empleado_prestamo) REFERENCES "Empleados" (id_empleado) ON DELETE RESTRICT,
        CONSTRAINT "FK_Prestamos_Libros_id_libro" FOREIGN KEY (id_libro) REFERENCES "Libros" (id_libro) ON DELETE RESTRICT,
        CONSTRAINT "FK_Prestamos_SolicitudPrestamo_id_solicitud" FOREIGN KEY (id_solicitud) REFERENCES "SolicitudPrestamo" (id_solicitud) ON DELETE RESTRICT,
        CONSTRAINT "FK_Prestamos_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE TABLE "Multas" (
        id_multa integer GENERATED BY DEFAULT AS IDENTITY,
        id_usuario integer NOT NULL,
        id_prestamo integer,
        monto numeric(10,2) NOT NULL,
        motivo character varying(255) NOT NULL,
        estado character varying(50) NOT NULL,
        fecha_generacion timestamp with time zone NOT NULL,
        id_empleado_resuelve integer,
        fecha_resolucion timestamp with time zone,
        observacion_resolucion character varying(255),
        CONSTRAINT "PK_Multas" PRIMARY KEY (id_multa),
        CONSTRAINT "FK_Multas_Empleados_id_empleado_resuelve" FOREIGN KEY (id_empleado_resuelve) REFERENCES "Empleados" (id_empleado) ON DELETE RESTRICT,
        CONSTRAINT "FK_Multas_Prestamos_id_prestamo" FOREIGN KEY (id_prestamo) REFERENCES "Prestamos" (id_prestamo) ON DELETE RESTRICT,
        CONSTRAINT "FK_Multas_Usuarios_id_usuario" FOREIGN KEY (id_usuario) REFERENCES "Usuarios" (id_usuario) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Administradores_id_cargo" ON "Administradores" (id_cargo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Administradores_id_usuario" ON "Administradores" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Auditoria_id_usuario" ON "Auditoria" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Cargos_nombre" ON "Cargos" (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Ejemplares_codigo" ON "Ejemplares" (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Ejemplares_id_libro" ON "Ejemplares" (id_libro);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Empleados_id_cargo" ON "Empleados" (id_cargo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Empleados_id_usuario" ON "Empleados" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Inventario_id_libro" ON "Inventario" (id_libro);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Libros_isbn" ON "Libros" (isbn);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Multas_id_empleado_resuelve" ON "Multas" (id_empleado_resuelve);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Multas_id_prestamo" ON "Multas" (id_prestamo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Multas_id_usuario" ON "Multas" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Notificaciones_id_usuario" ON "Notificaciones" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Permisos_codigo" ON "Permisos" (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Prestamos_id_ejemplar" ON "Prestamos" (id_ejemplar);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Prestamos_id_empleado_devolucion" ON "Prestamos" (id_empleado_devolucion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Prestamos_id_empleado_prestamo" ON "Prestamos" (id_empleado_prestamo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Prestamos_id_libro" ON "Prestamos" (id_libro);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Prestamos_id_solicitud" ON "Prestamos" (id_solicitud);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_Prestamos_id_usuario" ON "Prestamos" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Roles_nombre" ON "Roles" (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_RolPermiso_id_permiso" ON "RolPermiso" (id_permiso);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_SolicitudPrestamo_id_libro" ON "SolicitudPrestamo" (id_libro);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_SolicitudPrestamo_id_usuario" ON "SolicitudPrestamo" (id_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE INDEX "IX_UsuarioRol_id_rol" ON "UsuarioRol" (id_rol);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_cedula" ON "Usuarios" (cedula);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_email" ON "Usuarios" (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728031942_InitialPostgreSqlSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260728031942_InitialPostgreSqlSchema', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035539_PersistMultaTypeAndInventoryStates') THEN
    ALTER TABLE "Multas" ADD tipo character varying(50) NOT NULL DEFAULT 'Otra';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035539_PersistMultaTypeAndInventoryStates') THEN
    ALTER TABLE "Inventario" ADD cantidad_danada integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035539_PersistMultaTypeAndInventoryStates') THEN
    ALTER TABLE "Inventario" ADD cantidad_fuera_servicio integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035539_PersistMultaTypeAndInventoryStates') THEN
    ALTER TABLE "Inventario" ADD cantidad_perdida integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035539_PersistMultaTypeAndInventoryStates') THEN
    ALTER TABLE "Inventario" ADD cantidad_reservada integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035539_PersistMultaTypeAndInventoryStates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260728035539_PersistMultaTypeAndInventoryStates', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035912_AddAuthenticationLockout') THEN
    ALTER TABLE "Usuarios" ADD bloqueado_hasta timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035912_AddAuthenticationLockout') THEN
    ALTER TABLE "Usuarios" ADD intentos_acceso_fallidos integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728035912_AddAuthenticationLockout') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260728035912_AddAuthenticationLockout', '10.0.9');
    END IF;
END $EF$;
COMMIT;

