using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SIGEBI.Persistence.Context;

namespace SIGEBI.Persistence;

public static class LegacySchemaCompatibility
{
    public static async Task EnsureAsync(
        IServiceProvider services,
        CancellationToken cancellationToken = default)
    {
        await using var scope = services.CreateAsyncScope();
        var context = scope.ServiceProvider.GetRequiredService<SigebiContext>();

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "Cargos"
            (
                id_cargo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre character varying(100) NOT NULL,
                fecha_registro timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Cargos_nombre"
                ON "Cargos" (nombre);

            INSERT INTO "Cargos" (nombre, fecha_registro)
            VALUES
                ('Bibliotecario', CURRENT_TIMESTAMP),
                ('Administrador', CURRENT_TIMESTAMP)
            ON CONFLICT (nombre) DO NOTHING;

            CREATE TABLE IF NOT EXISTS "Administradores"
            (
                id_administrador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_usuario integer NOT NULL,
                id_cargo integer NOT NULL,
                fecha_registro timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_Administradores_Usuarios_id_usuario"
                    FOREIGN KEY (id_usuario)
                    REFERENCES "Usuarios" (id_usuario)
                    ON DELETE RESTRICT,
                CONSTRAINT "FK_Administradores_Cargos_id_cargo"
                    FOREIGN KEY (id_cargo)
                    REFERENCES "Cargos" (id_cargo)
                    ON DELETE RESTRICT
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Administradores_id_usuario"
                ON "Administradores" (id_usuario);

            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = 'Empleados'
                ) THEN
                    ALTER TABLE "Empleados"
                        ADD COLUMN IF NOT EXISTS id_cargo integer;
                    ALTER TABLE "Empleados"
                        ADD COLUMN IF NOT EXISTS fecha_registro
                        timestamp with time zone NOT NULL
                        DEFAULT CURRENT_TIMESTAMP;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'Empleados'
                          AND column_name = 'cargo'
                    ) THEN
                        INSERT INTO "Cargos" (nombre, fecha_registro)
                        SELECT DISTINCT COALESCE(
                            NULLIF(BTRIM(cargo), ''),
                            'Bibliotecario'),
                            CURRENT_TIMESTAMP
                        FROM "Empleados"
                        ON CONFLICT (nombre) DO NOTHING;

                        UPDATE "Empleados" AS empleado
                        SET id_cargo = cargo.id_cargo
                        FROM "Cargos" AS cargo
                        WHERE empleado.id_cargo IS NULL
                          AND cargo.nombre = COALESCE(
                              NULLIF(BTRIM(empleado.cargo), ''),
                              'Bibliotecario');
                    END IF;

                    INSERT INTO "Cargos" (nombre, fecha_registro)
                    VALUES ('Bibliotecario', CURRENT_TIMESTAMP)
                    ON CONFLICT (nombre) DO NOTHING;

                    UPDATE "Empleados"
                    SET id_cargo = (
                        SELECT id_cargo
                        FROM "Cargos"
                        WHERE nombre = 'Bibliotecario'
                    )
                    WHERE id_cargo IS NULL;

                    ALTER TABLE "Empleados"
                        ALTER COLUMN id_cargo SET NOT NULL;
                    CREATE INDEX IF NOT EXISTS "IX_Empleados_id_cargo"
                        ON "Empleados" (id_cargo);

                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'FK_Empleados_Cargos_id_cargo'
                    ) THEN
                        ALTER TABLE "Empleados"
                            ADD CONSTRAINT "FK_Empleados_Cargos_id_cargo"
                            FOREIGN KEY (id_cargo)
                            REFERENCES "Cargos" (id_cargo)
                            ON DELETE RESTRICT;
                    END IF;

                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = 'Administradores'
                ) THEN
                    ALTER TABLE "Administradores"
                        ADD COLUMN IF NOT EXISTS id_cargo integer;
                    ALTER TABLE "Administradores"
                        ADD COLUMN IF NOT EXISTS fecha_registro
                        timestamp with time zone NOT NULL
                        DEFAULT CURRENT_TIMESTAMP;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'Administradores'
                          AND column_name = 'cargo'
                    ) THEN
                        INSERT INTO "Cargos" (nombre, fecha_registro)
                        SELECT DISTINCT COALESCE(
                            NULLIF(BTRIM(cargo), ''),
                            'Administrador'),
                            CURRENT_TIMESTAMP
                        FROM "Administradores"
                        ON CONFLICT (nombre) DO NOTHING;

                        UPDATE "Administradores" AS administrador
                        SET id_cargo = cargo.id_cargo
                        FROM "Cargos" AS cargo
                        WHERE administrador.id_cargo IS NULL
                          AND cargo.nombre = COALESCE(
                              NULLIF(BTRIM(administrador.cargo), ''),
                              'Administrador');
                    END IF;

                    INSERT INTO "Cargos" (nombre, fecha_registro)
                    VALUES ('Administrador', CURRENT_TIMESTAMP)
                    ON CONFLICT (nombre) DO NOTHING;

                    UPDATE "Administradores"
                    SET id_cargo = (
                        SELECT id_cargo
                        FROM "Cargos"
                        WHERE nombre = 'Administrador'
                    )
                    WHERE id_cargo IS NULL;

                    ALTER TABLE "Administradores"
                        ALTER COLUMN id_cargo SET NOT NULL;
                    CREATE INDEX IF NOT EXISTS "IX_Administradores_id_cargo"
                        ON "Administradores" (id_cargo);

                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'FK_Administradores_Cargos_id_cargo'
                    ) THEN
                        ALTER TABLE "Administradores"
                            ADD CONSTRAINT "FK_Administradores_Cargos_id_cargo"
                            FOREIGN KEY (id_cargo)
                            REFERENCES "Cargos" (id_cargo)
                            ON DELETE RESTRICT;
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'Administrador'
                    ) THEN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'AdministradorCargo'
                        ) THEN
                            INSERT INTO "Administradores"
                                (id_usuario, id_cargo, fecha_registro)
                            SELECT
                                administrador.id_usuario,
                                COALESCE(
                                    cargo_asignado.id_cargo,
                                    (
                                        SELECT id_cargo
                                        FROM "Cargos"
                                        WHERE nombre = 'Administrador'
                                    )),
                                CURRENT_TIMESTAMP
                            FROM "Administrador" AS administrador
                            LEFT JOIN "AdministradorCargo" AS cargo_asignado
                                ON cargo_asignado.id_administrador =
                                   administrador.id_administrador
                            ON CONFLICT (id_usuario) DO NOTHING;
                        ELSE
                            INSERT INTO "Administradores"
                                (id_usuario, id_cargo, fecha_registro)
                            SELECT
                                administrador.id_usuario,
                                (
                                    SELECT id_cargo
                                    FROM "Cargos"
                                    WHERE nombre = 'Administrador'
                                ),
                                CURRENT_TIMESTAMP
                            FROM "Administrador" AS administrador
                            ON CONFLICT (id_usuario) DO NOTHING;
                        END IF;
                    END IF;
                END IF;
            END
            $$;
            """,
            cancellationToken);
    }
}
